import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Quagga from 'quagga'; // ES6
import React, { useEffect, useRef, useState } from "react";
import Button from '@mui/material/Button';



export default function Home() {

  const videoRef = useRef(null)
  const [status, setStatus] = useState(null);
  const [barCode, setBarCode] = useState(null);

  const resetScan = () => {
    setStatus(null);
    setBarCode(null);
  }

  const stopScan = () => {
    Quagga.stop();
  }

  const stopAndReset = () => {
    stopScan();
    resetScan();
  }

  const startScan = () => {
    resetScan();
    Quagga.init({
      inputStream : {
        name : "Live",
        type : "LiveStream",
        target: videoRef.current,    // Or '#yourElement' (optional)
      },
      decoder : {
        readers : ["code_128_reader"]
      }
    }, function(err) {
      if (err) {
        console.log(err);
        return
      }
      console.log("Initialization finished. Ready to start");
      Quagga.start();
      setStatus('Scanning...')
    });

    Quagga.onProcessed((result) => {
      console.log('onProcessed', result)
    });

    Quagga.onDetected((result) => {
      setStatus('Detected a Barcode!')
      console.log('onDetected', result.codeResult.code)
      setBarCode(result.codeResult.code);
      stopScan();
    })
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Barcode Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {status !== 'Scanning...' &&
          <Button onClick={startScan} variant="outlined">{!barCode ?  'Scan a Barcode' : 'Scan another Barcode'}</Button>
        }
        <div style={status === 'Scanning...' ? {display: 'block' }: {display: 'none'}} ref={videoRef} id="section">
        </div>
        <div className="status">{status}</div>
        {barCode &&
          <div className="barcode">
            {barCode}
          </div>
        }
        {status === 'Scanning...' &&
          <Button onClick={stopAndReset} variant="outlined" color="secondary">Stop</Button>
        }

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
